### ISSUE TITLE
Pre-trained model?

### ISSUE THREAD

**Issue by roimulia2** [Tengfei-Wang/external-internal-inpainting#4]
Hey there! Loved the paper.

Is there access to the pre-trained model?

Thanks!

**Comment by Tengfei-Wang** [comment]
Hi,
The internal colorization model is individual for each image, and you can try to colorize your image with our code (~30 seconds).
As for the reconstruction part, since our method is not limited to a specific backbone model,  we now do not release the pre-trained models. For a quick start, maybe you can simply convert an inpainting result from other methods to grayscale, and re-colorize it with our method to see if there is any improvement.
